### ISSUE TITLE
.txt → .md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [Valerii-Nozdrenkov/BSA-17-.NET.-Lecture-1---Git#2]
@Valerii-Nozdrenkov Hey, what do you think about switching to **.md** for file extension? You could then apply some Markdown formatting so it'll look so much fancier. "So look, much fancy, very MD" kind of thing.

**Comment by Valerii-Nozdrenkov** [comment]
The files have been renamed to .md extension.
