### ISSUE TITLE
Create a review on document "Рецензия на книгу Джона Скита “C# in Depth”, 2nd E.md"

### ISSUE THREAD

**Issue by Valerii-Nozdrenkov** [Valerii-Nozdrenkov/BSA-17-.NET.-Lecture-1---Git#5]

**Comment by Valerii-Nozdrenkov** [comment]
Hi Valerii, please make a review on this doc. Then we can discuss it on daily meeting tomorrow. Thanks.

**Comment by Valerii-Nozdrenkov** [comment]
Velerii, there are some issues in text formatting. Please, check it.

**Comment by Valerii-Nozdrenkov1** [comment]
Hi, I have checked the formatting in online Markdown previewer. There was everything OK.

**Comment by Valerii-Nozdrenkov** [comment]
Ok, I'll close the issue.
